// demo/client/ng-cargoplane-demo/src/app/chat/chat-window.component.ts
import {Component, OnInit, Input, OnDestroy} from '@angular/core';
import {ChatService} from './chat.service';
import {ChatMessage} from '../model/chat';
import {Subscription} from 'rxjs';

@Component({
  selector: 'app-chat-window',
  templateUrl: './chat-window.component.html'
})
export class ChatWindowComponent implements OnInit, OnDestroy {
  @Input() topic: string;

  chats: string[];
  subscription?: Subscription;

  constructor(private chatService: ChatService) {
  }

  ngOnInit() {
    this.chats = [];

    this.subscription = this.chatService.observe(this.topic)
      .subscribe(message => {
        this.chats.push((message as ChatMessage).text);
        console.log(message);
      });
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
      this.subscription = undefined;
    }
  }
}

<div>
  <ul>
    <app-chat-line *ngFor="let txt of chats"  [line]="txt"></app-chat-line>
  </ul>
</div>

// demo/client/react-cargoplane-demo/src/chat/chat-window.jsx
import React from 'react';

import ChatLine from './chat-line';
import ChatService from "./chat.service";

class ChatWindow extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            chats: []
        }
    }

    componentDidMount() {
        ChatService.observe(this.props.topic)
            .subscribe(message => {
                console.log(message);
                let chats = this.state.chats;
                chats.push((message).text);
                this.setState({
                    chats: chats 
                });
            });
    }

    componentWillUnmount() {

    }

    render() {
        return (
            <div>
                <ul className="chat-list">
                    {this.state.chats.map((line, idx) =>
                        <ChatLine key={idx.toString()} line={line}></ChatLine>
                    )}
                </ul>
            </div>
        )
    }
}

export default ChatWindow;
