// demo/client/react-cargoplane-demo/src/chat/chat.jsx
import React from 'react';

import ChatWindow from './chat-window';
import ChatService from "./chat.service";

class Chat extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            text: '',
            topic: 'chattopic/mqtt',
        };

        this.handleTextChange = this.handleTextChange.bind(this);
        this.handleTopicChange = this.handleTopicChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleTextChange(event) {
        this.setState({text: event.target.value});
    }

    handleTopicChange(event) {
        this.setState({topic: event.target.value});
    }

    handleSubmit(event) {
        console.log("submit");
        event.preventDefault();
        console.log(this.state.topic, this.state.text);
        ChatService.publish(this.state.topic, this.state.text);
        this.setState({
            text: ""
        });
    }

    render() {
        return (
            <div>
                <form onSubmit={this.handleSubmit}>
                    <label>Publish:
                        <input value={this.state.text} onChange={this.handleTextChange} placeholder="message" />
                    </label>
                    <label>
                        via
                        <select value={this.state.topic} onChange={this.handleTopicChange}>
                            <option value="chattopic/mqtt">MQTT</option>
                            <option value="chattopic/lambda">AWS Lambda</option>
                        </select>
                        <input type="submit" value="Submit"/>
                    </label>
                </form>
                <p></p>
                <div className="description">When sending a message via MQTT, the message will publish directly to MQTT from the browser to the topic <code>chattopic/mqtt</code>.</div>
                <div className="description">When sending a message via AWS, the message will be posted to an AWS Lambda via API Gateway.  The Lambda will then publish the message to the topic <code>chattopic/lambda</code>.</div>

                <table className="chatwindows">
                    <tbody>
                        <tr>
                            <td>
                                <h2>MQTT</h2>
                                <div className="description">This window is subscribing to the topic <code>chattopic/mqtt</code>.    </div>
                                <ChatWindow topic="chattopic/mqtt"></ChatWindow>
                            </td>
                            <td>
                                <h2>AWS Lambda</h2>
                                <div className="description">This window is subscribing to the topic <code>chattopic/lambda</code>.   </div>
                                <ChatWindow topic="chattopic/lambda"></ChatWindow>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        )
    }
}

export default Chat;

// demo/client/ng-cargoplane-demo/src/app/chat/chat.component.ts
import {Component} from '@angular/core';
import {ChatService} from './chat.service';
import {FormGroup, FormControl} from '@angular/forms';

@Component({
  selector: 'app-chat',
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.css']
})
export class ChatComponent {
  chatForm = new FormGroup({
    topic: new FormControl('chattopic/mqtt'),
    text: new FormControl('')
  });

  constructor(private chatService: ChatService) {
  }

  onSubmit() {
    const topic = this.chatForm.value.topic;

    // TODO: Use EventEmitter with form value
    console.log('sending: ', this.chatForm.value);
    if (this.chatForm.value.text) {
      this.chatService.publish(topic, this.chatForm.value.text);
      this.chatForm.controls.text.patchValue('');
    }
  }
}

<div>
  <form [formGroup]="chatForm" (ngSubmit)="onSubmit()"> 
    <label>Publish:
      <input formControlName="text" placeholder="message"/> 
    </label>
    <label>
      via
      <select formControlName="topic">
        <option value="chattopic/mqtt">MQTT</option>
        <option value="chattopic/lambda">AWS Lambda</option>
      </select>
      <button type="submit">Submit</button>
    </label>
  </form>
  <p></p>
  <div class="description">When sending a message via MQTT, the message will publish directly to MQTT from the browser to the topic <code>chattopic/mqtt</code>.</div>
  <div class="description">When sending a message via AWS, the message will be posted to an AWS Lambda via API Gateway.  The Lambda will then publish the message to the topic <code>chattopic/lambda</code>.</div>

  <table class="chatwindows">
    <tbody>
      <tr>
        <td>
          <h2>MQTT</h2>
          <div class="description">This window is subscribing to the topic <code>chattopic/mqtt</code>.    </div>
          <app-chat-window topic="chattopic/mqtt"></app-chat-window>
        </td>
        <td>
          <h2>AWS Lambda</h2>
          <div class="description">This window is subscribing to the topic <code>chattopic/lambda</code>.   </div>
          <app-chat-window topic="chattopic/lambda"></app-chat-window>
        </td>
      </tr>
    </tbody>
  </table>  
</div>
